import React from 'react'
import CIcon from '@coreui/icons-react'
import { NavLink } from 'react-router-dom'

const _nav = [
  {
    _component: 'CNavTitle',
    anchor: 'Nihongo365 Chat',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Chat',
    to: '/chat',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Trang chủ',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Tổng quan',
    to: '/dashboard',
    icon: <CIcon name="cil-speedometer" customClasses="nav-icon" />,
    // badge: {
    //   color: 'info',
    //   text: 'NEW',
    // },
  },
  // {
  //   _component: 'CNavTitle',
  //   anchor: 'Theme',
  // },
  // {
  //   _component: 'CNavItem',
  //   as: NavLink,
  //   anchor: 'Colors',
  //   to: '/theme/colors',
  //   icon: <CIcon name="cil-drop" customClasses="nav-icon" />,
  // },
  // {
  //   _component: 'CNavItem',
  //   as: NavLink,
  //   anchor: 'Typography',
  //   to: '/theme/typography',
  //   icon: <CIcon name="cil-pencil" customClasses="nav-icon" />,
  // },
  // {
  //   _component: 'CNavTitle',
  //   anchor: 'Components',
  // },
  // {
  //   _component: 'CNavGroup',
  //   as: NavLink,
  //   anchor: 'Base',
  //   to: '/to',
  //   icon: <CIcon name="cil-puzzle" customClasses="nav-icon" />,
  //   items: [
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Accordion',
  //       to: '/base/accordion',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Breadcrumb',
  //       to: '/base/breadcrumbs',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Cards',
  //       to: '/base/cards',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Carousel',
  //       to: '/base/carousels',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Collapse',
  //       to: '/base/collapses',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'List group',
  //       to: '/base/list-groups',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Navs & Tabs',
  //       to: '/base/navs',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Pagination',
  //       to: '/base/paginations',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Popovers',
  //       to: '/base/popovers',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Progress',
  //       to: '/base/progress',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Spinners',
  //       to: '/base/spinners',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Tables',
  //       to: '/base/tables',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Tooltips',
  //       to: '/base/tooltips',
  //     },
  //   ],
  // },
  // {
  //   _component: 'CNavGroup',
  //   anchor: 'Buttons',
  //   icon: <CIcon name="cil-cursor" customClasses="nav-icon" />,
  //   items: [
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Buttons',
  //       to: '/buttons/buttons',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Buttons groups',
  //       to: '/buttons/button-groups',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Dropdowns',
  //       to: '/buttons/dropdowns',
  //     },
  //   ],
  // },
  // {
  //   _component: 'CNavGroup',
  //   anchor: 'Forms',
  //   icon: <CIcon name="cil-notes" customClasses="nav-icon" />,
  //   items: [
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Form Control',
  //       to: '/forms/form-control',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Select',
  //       to: '/forms/select',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Checks & Radios',
  //       to: '/forms/checks-radios',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Range',
  //       to: '/forms/range',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Input Group',
  //       to: '/forms/input-group',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Floating Labels',
  //       to: '/forms/floating-labels',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Layout',
  //       to: '/forms/layout',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Validation',
  //       to: '/forms/validation',
  //     },
  //   ],
  // },
  // {
  //   _component: 'CNavItem',
  //   as: NavLink,
  //   anchor: 'Charts',
  //   to: '/charts',
  //   icon: <CIcon name="cil-chart-pie" customClasses="nav-icon" />,
  // },
  // {
  //   _component: 'CNavGroup',
  //   anchor: 'Icons',
  //   icon: <CIcon name="cil-star" customClasses="nav-icon" />,
  //   items: [
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'CoreUI Free',
  //       to: '/icons/coreui-icons',
  //       badge: {
  //         color: 'success',
  //         text: 'NEW',
  //       },
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'CoreUI Flags',
  //       to: '/icons/flags',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'CoreUI Brands',
  //       to: '/icons/brands',
  //     },
  //   ],
  // },
  // {
  //   _component: 'CNavGroup',
  //   anchor: 'Notifications',
  //   icon: <CIcon name="cil-bell" customClasses="nav-icon" />,
  //   items: [
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Alerts',
  //       to: '/notifications/alerts',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Badges',
  //       to: '/notifications/badges',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Modal',
  //       to: '/notifications/modals',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Toasts',
  //       to: '/notifications/toasts',
  //     },
  //   ],
  // },
  // {
  //   _component: 'CNavItem',
  //   as: NavLink,
  //   anchor: 'Widgets',
  //   to: '/widgets',
  //   icon: <CIcon name="cil-calculator" customClasses="nav-icon" />,
  //   badge: {
  //     color: 'info',
  //     text: 'NEW',
  //   },
  // },
  // {
  //   _component: 'CNavTitle',
  //   anchor: 'Extras',
  // },
  // {
  //   _component: 'CNavGroup',
  //   anchor: 'Pages',
  //   icon: <CIcon name="cil-star" customClasses="nav-icon" />,
  //   items: [
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Login',
  //       to: '/login',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Register',
  //       to: '/register',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Error 404',
  //       to: '/404',
  //     },
  //     {
  //       _component: 'CNavItem',
  //       as: NavLink,
  //       anchor: 'Error 500',
  //       to: '/500',
  //     },
  //   ],
  // },
  {
    _component: 'CNavTitle',
    anchor: 'Bảng chữ động',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Tra cứu',
    to: '/characters/search',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Kana (177)',
    to: '/characters/kana',
    icon: <CIcon name="cil-pencil" customClasses="nav-icon" />,
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Jōyō kanji (2136)',
    to: '/characters/joyokanji',
    icon: <CIcon name="cil-pencil" customClasses="nav-icon" />,
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Jinmeiyō (862)',
    to: '/characters/jinmeiyo',
    icon: <CIcon name="cil-pencil" customClasses="nav-icon" />,
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Furigana',
    to: '/furigana',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Chữ Hán',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thẻ chữ Hán',
    to: '/cards',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm chữ Hán',
    to: '/cards/addCard',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Bài học chữ Hán',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Bài học chữ Hán',
    to: '/boards',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài học',
    to: '/boards/addBoard',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Chủ đề từ vựng',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Quản lý chủ đề',
    to: '/topics',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Bài học nghe',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài học nghe',
    to: '/listening-boards',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài học nghe',
    to: '/listening-boards/addBoard',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Bài học hội thoại',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài học hội thoại',
    to: '/dialog-boards',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài học hội thoại',
    to: '/dialog-boards/addBoard',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Bài luyện đọc',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài luyện đọc',
    to: '/reading-boards',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài học luyện đọc',
    to: '/reading-boards/addBoard',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Bài học ngữ pháp',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài ngữ pháp',
    to: '/grammar',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài ngữ pháp',
    to: '/grammar/addGrammar',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Từ điển',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Quản lý từ điển',
    to: '/dictionary',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Luyện thi từng phần',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài thi theo phần',
    to: '/sub-tests',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài',
    to: '/sub-tests/addSubTest',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Thi thử',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài thi thử',
    to: '/trial-tests',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm bài',
    to: '/trial-tests/addTrialTest',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Chuyên mục báo mạng',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách chuyên mục',
    to: '/news-categories',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Thêm chuyên mục',
    to: '/news-categories/addCategory',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Bài viết báo mạng',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Danh sách bài viết',
    to: '/news',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Viết bài',
    to: '/news/addNews',
  },
  {
    _component: 'CNavTitle',
    anchor: 'Khác',
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Đăng xuất',
    to: '/logout',
  },
]

export default _nav
