module.exports.Token = require('./token.model');
module.exports.User = require('./user.model');
module.exports.Card = require('./card.model');
module.exports.Board = require('./board.model');
const { Topic, Chapter, Lesson, Vocab } = require('./topic.model');
module.exports.Topic = Topic;
module.exports.Chapter = Chapter;
module.exports.Lesson = Lesson;
module.exports.Vocab = Vocab;
